### ISSUE TITLE
[Bug]: remote connections not available in dropdown

### ISSUE THREAD

**Issue by ghost** [wavetermdev/waveterm#1605]
### Current Behavior

Despite the connection manager being populated with ssh-connections when using the GUI to connect to a remote machine, no remote connections are showing up in the dropdown, just the "local" section.

![waveterm-connections](https://github.com/user-attachments/assets/64063454-a78c-4e1e-a5aa-252e7c744058)
![waveterm-connectionsmanager](https://github.com/user-attachments/assets/41977188-dca0-4a63-abb7-9036a197196b)

### Expected Behavior

Have the dropdown-menu be populated with remote ssh-connections after setting them up the first time and being added to the management file.

### Steps To Reproduce

1. Manually connect to a remote machine via SSH via GUI.
2. Have it automatically be added to the management file
3. Dropdown list for remote connections is still empty.

### Wave Version

v0.10.4

### Platform

Linux

### OS Version/Distribution

Ubuntu 24.04

### Architecture

x64

### Anything else?

Problem is the same, whether using the .deb- oder snap-package.

### Questionnaire

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

**Comment by esimkowitz** [comment]
Could you send your log file to support@waveterm.dev? You can find your logfile location by running `wsh wavepath log` from within Wave

**Comment by heinsenberg82** [comment]
I'm having the same issue

**Comment by dorel-david** [comment]
me too, i have the same issue, using mac M2

**Comment by esimkowitz** [comment]
Same ask, please send us your logs so we can investigate further

**Comment by heinsenberg82** [comment]
> Same ask, please send us your logs so we can investigate further

sent

**Comment by dorel-david** [comment]
> Same ask, please send us your logs so we can investigate further

sent

**Comment by esimkowitz** [comment]
Is it always empty or does it populate if you close the connection switcher and reopen it?

**Comment by dorel-david** [comment]
> Is it always empty or does it populate if you close the connection switcher and reopen it?

from my side, it is always only show the local one, even if connected to the remote server, the list still show the local one(even reopen).
<img width="1370" alt="image" src="https://github.com/user-attachments/assets/e71d3fa7-e886-43b2-b546-bb121e3e5c45" />
<img width="1370" alt="image" src="https://github.com/user-attachments/assets/e91e45de-3f2e-406f-b725-96cc8bb029c6" />
<img width="457" alt="image" src="https://github.com/user-attachments/assets/f0bf084a-f5bc-4673-bf89-7e19b80b02aa" />

**Comment by esimkowitz** [comment]
What does your ~/.ssh/config look like?

**Comment by dorel-david** [comment]
> What does your ~/.ssh/config look like?

i don't have this file, but i had look in the doc, it should support internal config/connections.json file right?

**Comment by esimkowitz** [comment]
Does the file exist? Or is it missing completely?

**Comment by dorel-david** [comment]
> Does the file exist? Or is it missing completely?

it is missing completely, should i create it manually?

**Comment by heinsenberg82** [comment]
Let me say that just f%4#ng out of nowhere my remote connection is now appearing on the dropdown.... 😅🤷‍♂️

**Comment by dorel-david** [comment]
me, too, after a create the ~/.ssh/config file, and create a connection to the file, now it show in the dropdown, even the internal connection can show. but when i delete the config file content(file still exist), the dropdown connections disappear again.

**Comment by heinsenberg82** [comment]
> me, too, after a create the ~/.ssh/config file, and create a connection to the file, now it show in the dropdown, even the internal connection can show. but when i delete the config file content(file still exist), the dropdown connections disappear again.

Weird. I already had a `~/.ssh/config` file.

**Comment by dorel-david** [comment]
> > me, too, after a create the ~/.ssh/config file, and create a connection to the file, now it show in the dropdown, even the internal connection can show. but when i delete the config file content(file still exist), the dropdown connections disappear again.
> 
> Weird. I already had a `~/.ssh/config` file. Nothing changed.

you need to fill something in the config file, cannot let it stay empty. then you can show:

**Comment by dorel-david** [comment]
> > me, too, after a create the ~/.ssh/config file, and create a connection to the file, now it show in the dropdown, even the internal connection can show. but when i delete the config file content(file still exist), the dropdown connections disappear again.
> 
> Weird. I already had a `~/.ssh/config` file. Nothing changed.

you need to fill something in the config file, cannot let it stay empty. then you can show:
<img width="311" alt="image" src="https://github.com/user-attachments/assets/6303740d-8c77-4b4f-a22f-db0b5238d4ac" />

**Comment by heinsenberg82** [comment]
> > > me, too, after a create the ~/.ssh/config file, and create a connection to the file, now it show in the dropdown, even the internal connection can show. but when i delete the config file content(file still exist), the dropdown connections disappear again.
> > 
> > Weird. I already had a `~/.ssh/config` file. Nothing changed.
> 
> you need to fill something in the config file, cannot let it stay empty. then you can show:
> <img width="311" alt="image" src="https://github.com/user-attachments/assets/6303740d-8c77-4b4f-a22f-db0b5238d4ac" />
> 

That's my point, my Wave Terminal config file was also already populated. I don't know what have change in order to the dropdown is properly working now.

**Comment by esimkowitz** [comment]
this should be fixed in the latest beta, can you check if you still have the issue there?

**Comment by esimkowitz** [comment]
Checking again, is this fixed? Going to close next week if I don't hear back.

**Comment by esimkowitz** [comment]
Are you enabling WSH for your remote connections? Only connections with WSH enabled will show up in the preview widget

**Comment by heinsenberg82** [comment]
> Are you enabling WSH for your remote connections? Only connections with WSH enabled will show up in the preview widget

How do I do that? Where is this documented?

**Comment by heinsenberg82** [comment]
> Are you enabling WSH for your remote connections? Only connections with WSH enabled will show up in the preview widget

For reasons I don't know, this was my configuration:

```
"user@192.168.28.12:2222": {
    "conn:wshenabled": false
  },
```

After I changed `conn:wshenabled` to `true`, it seems to have a conflict with ZSH:

![Image](https://github.com/user-attachments/assets/c3617248-c45e-4dde-8ba5-1ae19bbbaf16)

And now, when I try to open the `files` window, the window shows this error:

```
Error: no route for "conn:user@192.168.28.12:2222"

Error: no route for "conn:user@192.168.28.12:2222"
    at file:///C:/Users/user/AppData/Local/Programs/waveterm/resources/app.asar/dist/frontend/assets/index-q3GoV2Ly.js:20517:19
    at Generator.next (<anonymous>)
    at resume (file:///C:/Users/user/AppData/Local/Programs/waveterm/resources/app.asar/dist/frontend/assets/index-q3GoV2Ly.js:66:29)
    at file:///C:/Users/user/AppData/Local/Programs/waveterm/resources/app.asar/dist/frontend/assets/index-q3GoV2Ly.js:67:68

```

**Comment by esimkowitz** [comment]
Does restarting Wave help?

**Comment by heinsenberg82** [comment]
> Does restarting Wave help?

Nope. Actually, restarting the application now presents this error popup, both in the terminal and file views.

```
Disconnected from "user@192.168.28.12:2222"

unable to use wsh: error opening domain socket listener: unable to request connection domain socket: ssh: streamlocal-forward@openssh.com request denied by peer

[Button: "always disable wsh"]
```

Btw, there's nothing wrong with my SSH connection, I can connect normally on my server.

**Comment by esimkowitz** [comment]
Can you share the (sanitized) config for your remote? Also what OS are you running on the remote?

**Comment by heinsenberg82** [comment]
>Can you share the (sanitized) config for your remote?

Do you mean the `.waveterm\config\connections.json` file?

```json
{
  "user@192.168.28.12:2222": {
    "conn:wshenabled": true
  },
  "wsl://Debian": {
    "conn:wshenabled": true
  }
}
```

>Also what OS are you running on the remote?

It's an Openmediavault 7 NAS. `Debian GNU/Linux 12 (bookworm) x86_64` OS.

**Comment by esimkowitz** [comment]
Sorry, I meant your `~/.ssh/config` configuration

**Comment by heinsenberg82** [comment]
>Sorry, I meant your ~/.ssh/config configuration. Obviously leave out anything sensitive, I just want to see what options you're using

No worries. Here it is:

```
Host 192.168.28.12
  HostName 192.168.28.12
  Port 2222
  User user
```

**Comment by Giftia** [comment]
> > Does restarting Wave help?
> 
> Nope. Actually, restarting the application now presents this error popup, both in the terminal and file views.
> 
> ```
> Disconnected from "user@192.168.28.12:2222"
> 
> unable to use wsh: error opening domain socket listener: unable to request connection domain socket: ssh: streamlocal-forward@openssh.com request denied by peer
> 
> [Button: "always disable wsh"]
> ```
> 
> Btw, there's nothing wrong with my SSH connection, I can connect normally on my server.

I have the same issue when using Dropbear as the SSH server.
```
# dropbear -V
Dropbear v2022.82
```
The device uses Dropbear instead of a standard SSH server, which may be related to this problem.
