### ISSUE TITLE
Cannot find bash on creating new connection

### ISSUE THREAD

**Issue by ToontjeM** [wavetermdev/waveterm#703]
**Describe the bug**
When creating a new connection and using this connection for the first time Wave looks for /usr/local/bin/bash which doesn't exist on Linux servers.

**To Reproduce**
1. Create new connectio to Linux server
2. Try connecting using this connection
3. The following error shows up:

```
wave> console for connection [proxmox]
wave> connecting to root@192.168.0.101...
wave> error, invalid packet received from waveshell client: raw[bash: line 1: /usr/local/bin/bash: No such file or directory]
```

**Expected behavior**
A new SSH connection to the target server is created.

**Screenshots**
<img width="718" alt="image" src="https://github.com/wavetermdev/waveterm/assets/98271783/20f415c2-538d-4e5e-9c97-fb988733ff05">

**Desktop (please complete the following information):**
<img width="261" alt="image" src="https://github.com/wavetermdev/waveterm/assets/98271783/2ca2e891-f8b1-4d9d-a9e7-c6c67302ece3"> - Version [e.g. v0.5.0]
<img width="375" alt="image" src="https://github.com/wavetermdev/waveterm/assets/98271783/b57c6920-ecee-4731-8929-52c7f90c714a">

**Additional context**
Happens to all servers. Please explain how to get the waveshell on the remote machine.

**Comment by ToontjeM** [comment]
Reinstall gives me:
```
wave> fatal error, this should not happen. if it does, please reach out to us in our discord or open an issue on our github

error:
assignment to entry in nil map

stack trace:
goroutine 8114 [running]:
runtime/debug.Stack()
        /Users/runner/hostedtoolcache/go/1.22.0/arm64/src/runtime/debug/stack.go:24 +0x5e
github.com/wavetermdev/waveterm/wavesrv/pkg/remote.(*WaveshellProc).RunInstall.func1()
        /Users/runner/work/waveterm/waveterm/wavesrv/pkg/remote/remote.go:1205 +0x48
panic({0x10fadccc0?, 0x10fb8e5c0?})
        /Users/runner/hostedtoolcache/go/1.22.0/arm64/src/runtime/panic.go:770 +0x132
github.com/wavetermdev/waveterm/wavesrv/pkg/remote.(*WaveshellProc).RunInstall(0xc0003e47e0, 0x0)
        /Users/runner/work/waveterm/waveterm/wavesrv/pkg/remote/remote.go:1289 +0x5f7
created by github.com/wavetermdev/waveterm/wavesrv/pkg/cmdrunner.RemoteInstallCommand in goroutine 8108
        /Users/runner/work/waveterm/waveterm/wavesrv/pkg/cmdrunner/cmdrunner.go:1800 +0xd8

```

Hope this helps.

**Comment by ToontjeM** [comment]
Just installed Wave on a new M1 and all seems to work fine.

**Comment by panisko** [comment]
> Reinstall gives me:
> 
> ```
> wave> fatal error, this should not happen. if it does, please reach out to us in our discord or open an issue on our github
> 
> error:
> assignment to entry in nil map
> 
> stack trace:
> goroutine 8114 [running]:
> runtime/debug.Stack()
>         /Users/runner/hostedtoolcache/go/1.22.0/arm64/src/runtime/debug/stack.go:24 +0x5e
> github.com/wavetermdev/waveterm/wavesrv/pkg/remote.(*WaveshellProc).RunInstall.func1()
>         /Users/runner/work/waveterm/waveterm/wavesrv/pkg/remote/remote.go:1205 +0x48
> panic({0x10fadccc0?, 0x10fb8e5c0?})
>         /Users/runner/hostedtoolcache/go/1.22.0/arm64/src/runtime/panic.go:770 +0x132
> github.com/wavetermdev/waveterm/wavesrv/pkg/remote.(*WaveshellProc).RunInstall(0xc0003e47e0, 0x0)
>         /Users/runner/work/waveterm/waveterm/wavesrv/pkg/remote/remote.go:1289 +0x5f7
> created by github.com/wavetermdev/waveterm/wavesrv/pkg/cmdrunner.RemoteInstallCommand in goroutine 8108
>         /Users/runner/work/waveterm/waveterm/wavesrv/pkg/cmdrunner/cmdrunner.go:1800 +0xd8
> ```
> 
> Hope this helps.

arm64 on intel machine ?

**Comment by ToontjeM** [comment]
Intel has the problem. M1 works fine.

**Comment by panisko** [comment]
This is the error message after wave built on intel:

error:
assignment to entry in nil map

stack trace:
goroutine 814 [running]:
runtime/debug.Stack()
        /usr/local/Cellar/go/1.23.0/libexec/src/runtime/debug/stack.go:26 +0x5e
github.com/wavetermdev/waveterm/wavesrv/pkg/remote.(*WaveshellProc).RunInstall.func1()
        /Volumes/Work/Projects/waveterm/wavesrv/pkg/remote/remote.go:1205 +0x48
panic({0x10350a600?, 0x1035c1860?})
        /usr/local/Cellar/go/1.23.0/libexec/src/runtime/panic.go:785 +0x132
github.com/wavetermdev/waveterm/wavesrv/pkg/remote.(*WaveshellProc).RunInstall(0xc0001fe240, 0x0)
        /Volumes/Work/Projects/waveterm/wavesrv/pkg/remote/remote.go:1289 +0x5dc
created by github.com/wavetermdev/waveterm/wavesrv/pkg/cmdrunner.RemoteInstallCommand in goroutine 808
        /Volumes/Work/Projects/waveterm/wavesrv/pkg/cmdrunner/cmdrunner.go:1800 +0xd8
