### ISSUE TITLE
Remote connection with password fails

### ISSUE THREAD

**Issue by akhiln28** [wavetermdev/waveterm#738]
**Describe the bug**
I am trying to connect to remote machine using ssh, username and password. 

**To Reproduce**
1. Go to connections in the sidebar
2. Click on the connection that is created earlier using username, host and password
3. Click on reinstall

wave> error, ssh cannot connect to client: ssh: handshake failed: remote host identification has changed

wave> fatal error, this should not happen. if it does, please reach out to us in our discord or open an issue on our github

error:
assignment to entry in nil map

stack trace:
goroutine 12415 [running]:
runtime/debug.Stack()
        /Users/runner/hostedtoolcache/go/1.22.0/arm64/src/runtime/debug/stack.go:24 +0x64
github.com/wavetermdev/waveterm/wavesrv/pkg/remote.(*WaveshellProc).RunInstall.func1()
        /Users/runner/work/waveterm/waveterm/wavesrv/pkg/remote/remote.go:1205 +0x40
panic({0x1007c8100?, 0x100879830?})
        /Users/runner/hostedtoolcache/go/1.22.0/arm64/src/runtime/panic.go:770 +0x124
github.com/wavetermdev/waveterm/wavesrv/pkg/remote.(*WaveshellProc).RunInstall(0x1400059b440, 0x0)
        /Users/runner/work/waveterm/waveterm/wavesrv/pkg/remote/remote.go:1289 +0x4e8
created by github.com/wavetermdev/waveterm/wavesrv/pkg/cmdrunner.RemoteInstallCommand in goroutine 12409
        /Users/runner/work/waveterm/waveterm/wavesrv/pkg/cmdrunner/cmdrunner.go:1800 +0xa8

**Expected behavior**
Remote connection should work. As I can ssh to it fine using username, ip address and password in the default terminal. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version [e.g. v0.5.0]

**Additional context**

**Comment by akhiln28** [comment]
Resolved it using `ssh-keygen -R <ipaddress>`
