### ISSUE TITLE
CocoaPods requires your terminal to be using UTF-8 encoding.

### ISSUE THREAD

**Issue by SlickSlime** [wavetermdev/waveterm#751]
**Describe the bug**
Cannot run `pod install --repo-update` command which works in macOS' native terminal.

**To Reproduce**
1. Create an Xcode project
2. Execute command: `pod install --repo-update` for the Xcode project

**Expected behavior**
Execute the command same as macOS' terminal.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 0.7.6

**Additional context**
Wave's terminal error:
```

    WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
    Consider adding the following to ~/.profile:

    export LANG=en_US.UTF-8
    
/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/unicode_normalize/normalize.rb:141:in `normalize': Unicode Normalization not appropriate for ASCII-8BIT (Encoding::CompatibilityError)
        from /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:167:in `unicode_normalize'
        from /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:167:in `installation_root'
        from /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:227:in `podfile_path'
        from /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/user_interface/error_report.rb:105:in `markdown_podfile'
        from /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/user_interface/error_report.rb:30:in `report'
        from /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:66:in `report_error'
        from /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/claide-1.1.0/lib/claide/command.rb:396:in `handle_exception'
        from /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/claide-1.1.0/lib/claide/command.rb:337:in `rescue in run'
        from /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/claide-1.1.0/lib/claide/command.rb:324:in `run'
        from /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
        from /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
        from /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/bin/pod:25:in `load'
        from /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/bin/pod:25:in `<main>'
/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/unicode_normalize/normalize.rb:141:in `normalize': Unicode Normalization not appropriate for ASCII-8BIT (Encoding::CompatibilityError)
        from /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:167:in `unicode_normalize'
        from /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:167:in `installation_root'
        from /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:227:in `podfile_path'
        from /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:206:in `podfile'
        from /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:160:in `verify_podfile_exists!'
        from /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command/install.rb:46:in `run'
        from /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
        from /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
        from /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
        from /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/bin/pod:25:in `load'
        from /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/bin/pod:25:in `<main>'
```

**Comment by kamushadenes** [comment]
Have you tried what the message asks?

```
    export LANG=en_US.UTF-8
```

You can run it without adding it to ~/.profile, but it will only work for the current terminal session.

Also, you might want to add to ~/.bash_profile or ~/.zprofile instead, depending on your shell.

**Comment by SlickSlime** [comment]
Thanks, adding that `export` works. 

Although I was expecting it to work out of the box. I don't remember adding this in [Warp](https://www.warp.dev/) terminal.

**Comment by kamushadenes** [comment]
This has no relation with the terminal emulator but with your shell.

Maybe Warp is using zsh and waveterm is using bash? You can select the shell in Connections. Glad it’s solved anyway.
